# 🟢 Solution: Implement ReLU

Reference solution for the ReLU activation function.

$$\text{ReLU}(x) = \max(0, x)$$

In [1]:
import torch

In [ ]:
# ✅ SOLUTION

def relu(x: torch.Tensor) -> torch.Tensor:
    #首先x>0
    return x * (x > 0).float()

In [3]:
# Verify
x = torch.tensor([-2., -1., 0., 1., 2.])
print("Input: ", x)
print("Output:", relu(x))

Input:  tensor([-2., -1.,  0.,  1.,  2.])
Output: tensor([-0., -0., 0., 1., 2.])


In [4]:
# Run judge
from torch_judge import check
check("relu")


🧪 Testing: Implement ReLU (Easy)
──────────────────────────────────────────────────
  ✅ [1/4] Basic values (2.9ms)
  ✅ [2/4] 2-D tensor (2.4ms)
  ✅ [3/4] Gradient check (29.1ms)
  ✅ [4/4] Performance (61.2ms)
──────────────────────────────────────────────────
  🎉 All 4 tests passed! (95.6ms total)
  Progress saved. Run status() to see your dashboard.



In [7]:
#note
#首先x>0会会出现一个布尔值，我们需要吧布尔值转为浮点数，然后再
print(x>0)
print((x>0).float())

tensor([False, False, False,  True,  True])
tensor([0., 0., 0., 1., 1.])


In [ ]:
#torch.float（）绝大多数情况下是不填的，如果想要去修改浮点数类型，可以用to来去做

x.to(dtype=torch.float32, device='mps')

tensor([0., 0., 0., 1., 1.])
