# 🟢 Easy: Implement Softmax

Implement the **Softmax** function from scratch.

$$\text{softmax}(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}}$$

### Signature
```python
def my_softmax(x: torch.Tensor, dim: int = -1) -> torch.Tensor:
    ...
```

### Rules
- Do **NOT** use `torch.softmax`, `F.softmax`, or `torch.nn.Softmax`
- Must be **numerically stable** (hint: subtract `max` before `exp`)

### Example
```
Input:  tensor([1., 2., 3.])
Output: tensor([0.0900, 0.2447, 0.6652])  # sums to 1.0
```

In [2]:
import torch

In [29]:
# ✏️ YOUR IMPLEMENTATION HERE
#首先应该是全部都转为指数，然后再求和，然后
def my_softmax(x : torch.tensor,dim = -1) -> torch.tensor:#入参是一个tensor，一个计算所在的维度（一般的softmax是在-1维度)
    max_x = torch.max(x,dim = dim,keepdim = True).values
    x -= max_x
    
    return torch.exp(x)/torch.sum(torch.exp(x),dim = dim,keepdim=True)

In [30]:
# 🧪 Debug
x = torch.tensor([1.0, 2.0, 3.0])
print("Output:", my_softmax(x, dim=-1))
print("Sum:   ", my_softmax(x, dim=-1).sum())  # should be ~1.0
print("Ref:   ", torch.softmax(x, dim=-1))

Output: tensor([0.0900, 0.2447, 0.6652])
Sum:    tensor(1.)
Ref:    tensor([0.0900, 0.2447, 0.6652])


In [31]:
# ✅ SUBMIT
from torch_judge import check
check("softmax")


🧪 Testing: Implement Softmax (Easy)
──────────────────────────────────────────────────
  ✅ [1/3] Basic 1-D (0.9ms)
  ✅ [2/3] 2-D along dim=-1 (0.4ms)
  ✅ [3/3] Numerical stability (1.2ms)
──────────────────────────────────────────────────
  🎉 All 3 tests passed! (2.6ms total)
  Progress saved. Run status() to see your dashboard.



In [ ]:
#try
x = torch.tensor([1.0, 2.0, 3.0])
print(torch.exp(x))

tensor([ 2.7183,  7.3891, 20.0855])


In [5]:
print(torch.sum(x,dim = -1))

tensor(6.)


In [9]:
print(torch.exp(x)/torch.sum(torch.exp(x),dim = -1))

tensor([0.0900, 0.2447, 0.6652])


### 这个问题在于，对于下面的，如果x是三个维度，求和后就剩两个维度，然后x/x后就是两个维度除两个维度，就会出错，在sum的时候加一个keepdim=True就行，这样会把后面的维度变成1


In [18]:
print(torch.sum(x,dim = -1,keepdim=True))

tensor([6.])


这个问题在于超过了浮点数，e的89次方就会直接超过浮点数报错，因为超过了，都变成了inf，可以先减去当前的最大值，然后再计算，随后答案是一样的，数学推导上，分子分母同乘一个常数（这里是 $e^{-\max(x)}$），Softmax 的最终计算结果保持严格等价不变。而在工程上，减去最大值后，所有参与指数计算的数值均被平移至 $\le 0$ 的区间。由于 $e^x$ 在 $x \le 0$ 时处于 $(0, 1]$ 之间，从而彻底根除了上溢出（Overflow）的可能性。

In [24]:
max_x = torch.max(x,dim = -1,keepdim=True)
print(max_x)

torch.return_types.max(
values=tensor([3.]),
indices=tensor([2]))


返回的是两个，一个value，一个是indices，即值和下标

In [27]:
max_x = torch.max(x,dim = -1,keepdim=True).values
print(max_x)

tensor([3.])


In [28]:
x -= max_x
print(x)

tensor([-2., -1.,  0.])
